package com.mycompany;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import com.mycompany.conexao.ConexaoDAO;
import java.sql.Date;
import java.sql.DriverManager;
import javax.swing.JTable;

public class AreaDoCliente extends javax.swing.JFrame {

    private CarrinhoDeCompras carrinhoFrame;

    List<ProdutoCarrinho> produtosSalvos = new ArrayList<>();
    public Mercado minhasCompras;

    /**
     * Creates new form TelaDeCompra
     */
    public AreaDoCliente() {
        initComponents();
        minhasCompras = new Mercado();
        carrinhoFrame = new CarrinhoDeCompras();
        carrinhoFrame.setVisible(true);
    }

    public AreaDoCliente(int aInt, Date date, String string) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnAdicionarAmeixa = new javax.swing.JButton();
        btnRemoverAmeixa = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();
        lblQuantidade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblQuantidadeAmeixa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQuantidadeCoca = new javax.swing.JLabel();
        btnAdicionarCoca = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRemoverCoca = new javax.swing.JButton();
        lblQuantidadeDetergente = new javax.swing.JLabel();
        btnAdicionarDetergente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRemoverDetergente = new javax.swing.JButton();
        btnRemoverGuarana = new javax.swing.JButton();
        btnAdicionarGuarana = new javax.swing.JButton();
        lblQuantidadeGuarana = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRemoverDesinfetante = new javax.swing.JButton();
        btnAdicionarDesinfetante = new javax.swing.JButton();
        lblQuantidadeDesinfetante = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQuantidadeBisnaga = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblQuantidadeCarne = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRemoverFini = new javax.swing.JButton();
        btnRemover7belo = new javax.swing.JButton();
        btnAdicionar7belo = new javax.swing.JButton();
        lblQuantidade7belo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAdicionarCarne = new javax.swing.JButton();
        btnRemoverCarne = new javax.swing.JButton();
        btnRemoverFrango = new javax.swing.JButton();
        btnAdicionarFrango = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblQuantidadeFrango = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblQuantidadePao = new javax.swing.JLabel();
        btnAdicionarPao = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnRemoverBisnaga = new javax.swing.JButton();
        btnRemoverPao = new javax.swing.JButton();
        btnAdicionarBisnaga = new javax.swing.JButton();
        lblQuantidadeFini = new javax.swing.JLabel();
        btnAdicionarFini = new javax.swing.JButton();
        lblValorTotalMorango = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblValorTotal1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblValorTotal2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblValorTotal3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblValorTotal4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblValorTotal5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblValorTotal6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblValorTotal7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblValorTotal8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblValorTotal9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblValorTotal10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblValorTotal11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnVerificarCPF = new javax.swing.JButton();
        btnSalvarCompras = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Insira seu CPF:");

        btnAdicionar.setText("Ad");
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionar.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionar.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Re");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnAdicionarAmeixa.setText("Ad");
        btnAdicionarAmeixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarAmeixa.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarAmeixa.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarAmeixa.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarAmeixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAmeixaActionPerformed(evt);
            }
        });

        btnRemoverAmeixa.setText("Re");
        btnRemoverAmeixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAmeixaActionPerformed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setName("CPF"); // NOI18N
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidade.setText("0");
        lblQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("O que deseja comprar?");

        jLabel3.setText("Morango");

        lblQuantidadeAmeixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeAmeixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeAmeixa.setText("0");
        lblQuantidadeAmeixa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeAmeixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Ameixa");

        lblQuantidadeCoca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeCoca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeCoca.setText("0");
        lblQuantidadeCoca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeCoca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAdicionarCoca.setText("Ad");
        btnAdicionarCoca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarCoca.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarCoca.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarCoca.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCocaActionPerformed(evt);
            }
        });

        jLabel5.setText("Coca Cola");

        btnRemoverCoca.setText("Re");
        btnRemoverCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCocaActionPerformed(evt);
            }
        });

        lblQuantidadeDetergente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeDetergente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeDetergente.setText("0");
        lblQuantidadeDetergente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeDetergente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAdicionarDetergente.setText("Ad");
        btnAdicionarDetergente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarDetergente.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarDetergente.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarDetergente.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarDetergente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDetergenteActionPerformed(evt);
            }
        });

        jLabel6.setText("Detergente");

        btnRemoverDetergente.setText("Re");
        btnRemoverDetergente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverDetergenteActionPerformed(evt);
            }
        });

        btnRemoverGuarana.setText("Re");
        btnRemoverGuarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverGuaranaActionPerformed(evt);
            }
        });

        btnAdicionarGuarana.setText("Ad");
        btnAdicionarGuarana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarGuarana.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarGuarana.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarGuarana.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarGuarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGuaranaActionPerformed(evt);
            }
        });

        lblQuantidadeGuarana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeGuarana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeGuarana.setText("0");
        lblQuantidadeGuarana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeGuarana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("Guarana");

        btnRemoverDesinfetante.setText("Re");
        btnRemoverDesinfetante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverDesinfetanteActionPerformed(evt);
            }
        });

        btnAdicionarDesinfetante.setText("Ad");
        btnAdicionarDesinfetante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarDesinfetante.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarDesinfetante.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarDesinfetante.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarDesinfetante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDesinfetanteActionPerformed(evt);
            }
        });

        lblQuantidadeDesinfetante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeDesinfetante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeDesinfetante.setText("0");
        lblQuantidadeDesinfetante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeDesinfetante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setText("Desinfetante");

        lblQuantidadeBisnaga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeBisnaga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeBisnaga.setText("0");
        lblQuantidadeBisnaga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeBisnaga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("Bisnaga");

        lblQuantidadeCarne.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeCarne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeCarne.setText("0");
        lblQuantidadeCarne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeCarne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setText("Fini");

        btnRemoverFini.setText("Re");
        btnRemoverFini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFiniActionPerformed(evt);
            }
        });

        btnRemover7belo.setText("Re");
        btnRemover7belo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemover7beloActionPerformed(evt);
            }
        });

        btnAdicionar7belo.setText("Ad");
        btnAdicionar7belo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar7belo.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionar7belo.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionar7belo.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionar7belo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar7beloActionPerformed(evt);
            }
        });

        lblQuantidade7belo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidade7belo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidade7belo.setText("0");
        lblQuantidade7belo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidade7belo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setText("7 belo");

        btnAdicionarCarne.setText("Ad");
        btnAdicionarCarne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarCarne.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarCarne.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarCarne.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCarneActionPerformed(evt);
            }
        });

        btnRemoverCarne.setText("Re");
        btnRemoverCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCarneActionPerformed(evt);
            }
        });

        btnRemoverFrango.setText("Re");
        btnRemoverFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFrangoActionPerformed(evt);
            }
        });

        btnAdicionarFrango.setText("Ad");
        btnAdicionarFrango.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarFrango.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarFrango.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarFrango.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFrangoActionPerformed(evt);
            }
        });

        jLabel12.setText("Carne");

        lblQuantidadeFrango.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeFrango.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeFrango.setText("0");
        lblQuantidadeFrango.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeFrango.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setText("Frango");

        lblQuantidadePao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadePao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadePao.setText("0");
        lblQuantidadePao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadePao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAdicionarPao.setText("Ad");
        btnAdicionarPao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarPao.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarPao.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarPao.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPaoActionPerformed(evt);
            }
        });

        jLabel14.setText("Pão");

        btnRemoverBisnaga.setText("Re");
        btnRemoverBisnaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverBisnagaActionPerformed(evt);
            }
        });

        btnRemoverPao.setText("Re");
        btnRemoverPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPaoActionPerformed(evt);
            }
        });

        btnAdicionarBisnaga.setText("Ad");
        btnAdicionarBisnaga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarBisnaga.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarBisnaga.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarBisnaga.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarBisnaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarBisnagaActionPerformed(evt);
            }
        });

        lblQuantidadeFini.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidadeFini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeFini.setText("0");
        lblQuantidadeFini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblQuantidadeFini.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAdicionarFini.setText("Ad");
        btnAdicionarFini.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarFini.setMaximumSize(new java.awt.Dimension(78, 75));
        btnAdicionarFini.setMinimumSize(new java.awt.Dimension(78, 75));
        btnAdicionarFini.setPreferredSize(new java.awt.Dimension(78, 75));
        btnAdicionarFini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFiniActionPerformed(evt);
            }
        });

        lblValorTotalMorango.setText("0");

        jLabel15.setText("R$");

        lblValorTotal1.setText("0");

        jLabel16.setText("R$");

        lblValorTotal2.setText("0");

        jLabel17.setText("R$");

        lblValorTotal3.setText("0");

        jLabel18.setText("R$");

        lblValorTotal4.setText("0");

        jLabel19.setText("R$");

        lblValorTotal5.setText("0");

        jLabel20.setText("R$");

        lblValorTotal6.setText("0");

        jLabel21.setText("R$");

        lblValorTotal7.setText("0");

        jLabel22.setText("R$");

        lblValorTotal8.setText("0");

        jLabel23.setText("R$");

        lblValorTotal9.setText("0");

        jLabel24.setText("R$");

        lblValorTotal10.setText("0");

        jLabel25.setText("R$");

        lblValorTotal11.setText("0");

        jLabel26.setText("R$");

        btnVerificarCPF.setText("Verificar");
        btnVerificarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarCPFActionPerformed(evt);
            }
        });

        btnSalvarCompras.setText("Salvar Compras e Ver Carrinho");
        btnSalvarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarComprasActionPerformed(evt);
            }
        });

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotal.setText("0");
        lblValorTotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblValorTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblValorTotal)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerificarCPF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAdicionarDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoverDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblQuantidadeDetergente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAdicionarCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoverCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblQuantidadeCoca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel15)
                                            .addGap(1, 1, 1)
                                            .addComponent(lblValorTotalMorango))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal4)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblQuantidadeAmeixa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdicionarDesinfetante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnRemoverDesinfetante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblQuantidadeDesinfetante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(btnAdicionarAmeixa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(24, 24, 24)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(lblValorTotal1))
                                                    .addComponent(btnRemoverAmeixa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal10))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblQuantidadeGuarana, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(btnAdicionarGuarana, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(20, 20, 20)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel20)
                                                    .addGap(1, 1, 1)
                                                    .addComponent(lblValorTotal5))
                                                .addComponent(btnRemoverGuarana, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(btnSalvarCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQuantidadeFini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuantidadePao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuantidadeCarne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionarCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal2))
                                    .addComponent(btnRemoverCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionarPao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal6))
                                    .addComponent(btnRemoverPao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionarFini, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal9))
                                    .addComponent(btnRemoverFini, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQuantidade7belo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdicionar7belo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal8))
                                    .addComponent(btnRemover7belo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblQuantidadeFrango, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnAdicionarFrango, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal3))
                                    .addComponent(btnRemoverFrango, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblQuantidadeBisnaga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnAdicionarBisnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblValorTotal7))
                                    .addComponent(btnRemoverBisnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificarCPF))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblValorTotalMorango)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidade)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdicionarCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoverCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQuantidadeCoca))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(lblValorTotal4)
                                .addComponent(jLabel19)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblValorTotal11)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeDetergente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblValorTotal3)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarFrango, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverFrango, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeFrango)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblValorTotal7)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarBisnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverBisnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeBisnaga)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblValorTotal8)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar7belo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemover7belo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidade7belo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblValorTotal2)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeCarne)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdicionarPao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoverPao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQuantidadePao))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValorTotal6)
                                    .addComponent(jLabel21))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblValorTotal9)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarFini, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverFini, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeFini))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblValorTotal1)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarAmeixa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverAmeixa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeAmeixa)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblValorTotal5)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarGuarana, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverGuarana, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeGuarana)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblValorTotal10)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarDesinfetante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverDesinfetante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeDesinfetante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade = minhasCompras.adicionarUmMorango();

        // Atualiza o preço do morango a cada clique
        double precoMorango = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidade.setText(String.valueOf(quantidade));
        lblValorTotalMorango.setText(String.valueOf(quantidade * precoMorango));

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade = minhasCompras.removerUmMorango();

        // Atualiza o preço do morango a cada clique
        double precoMorango = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidade.setText(String.valueOf(quantidade));
        lblValorTotalMorango.setText(String.valueOf(quantidade * precoMorango));

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarAmeixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAmeixaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade = minhasCompras.adicionarUmAmeixa();

        // Atualiza o preço do morango a cada clique
        double precoAmeixa = 8.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeAmeixa.setText(String.valueOf(quantidade));
        lblValorTotal1.setText(String.valueOf(quantidade * precoAmeixa));

    }//GEN-LAST:event_btnAdicionarAmeixaActionPerformed

    private void btnRemoverAmeixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAmeixaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade = minhasCompras.removerUmAmeixa();

        // Atualiza o preço do morango a cada clique
        double precoAmeixa = 8.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeAmeixa.setText(String.valueOf(quantidade));
        lblValorTotal1.setText(String.valueOf(quantidade * precoAmeixa));

    }//GEN-LAST:event_btnRemoverAmeixaActionPerformed

    private void btnAdicionarCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCocaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeCoca = minhasCompras.adicionarUmCoca();

        // Atualiza o preço do morango a cada clique
        double precoCoca = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeCoca.setText(String.valueOf(quantidadeCoca));
        lblValorTotal4.setText(String.valueOf(quantidadeCoca * precoCoca));

    }//GEN-LAST:event_btnAdicionarCocaActionPerformed

    private void btnRemoverCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCocaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeCoca = minhasCompras.removerUmCoca();

        // Atualiza o preço do morango a cada clique
        double precoCoca = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeCoca.setText(String.valueOf(quantidadeCoca));
        lblValorTotal4.setText(String.valueOf(quantidadeCoca * precoCoca));

    }//GEN-LAST:event_btnRemoverCocaActionPerformed

    private void btnAdicionarDetergenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDetergenteActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeDetergente = minhasCompras.adicionarUmDetergente();

        // Atualiza o preço do morango a cada clique
        double precoDetergente = 6.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeDetergente.setText(String.valueOf(quantidadeDetergente));
        lblValorTotal11.setText(String.valueOf(quantidadeDetergente * precoDetergente));

    }//GEN-LAST:event_btnAdicionarDetergenteActionPerformed

    private void btnRemoverDetergenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverDetergenteActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeDetergente = minhasCompras.removerUmDetergente();

        // Atualiza o preço do morango a cada clique
        double precoDetergente = 6.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeDetergente.setText(String.valueOf(quantidadeDetergente));
        lblValorTotal11.setText(String.valueOf(quantidadeDetergente * precoDetergente));

    }//GEN-LAST:event_btnRemoverDetergenteActionPerformed

    private void btnRemoverGuaranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverGuaranaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeGuarana = minhasCompras.removerUmGuarana();

        // Atualiza o preço do morango a cada clique
        double precoGuarana = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeGuarana.setText(String.valueOf(quantidadeGuarana));
        lblValorTotal5.setText(String.valueOf(quantidadeGuarana * precoGuarana));

    }//GEN-LAST:event_btnRemoverGuaranaActionPerformed

    private void btnAdicionarGuaranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGuaranaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeGuarana = minhasCompras.adicionarUmGuarana();

        // Atualiza o preço do morango a cada clique
        double precoGuarana = 10.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeGuarana.setText(String.valueOf(quantidadeGuarana));
        lblValorTotal5.setText(String.valueOf(quantidadeGuarana * precoGuarana));

    }//GEN-LAST:event_btnAdicionarGuaranaActionPerformed

    private void btnRemoverDesinfetanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverDesinfetanteActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeDesinfetante = minhasCompras.removerUmDesinfetante();

        // Atualiza o preço do morango a cada clique
        double precoDesinfetante = 15.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeDesinfetante.setText(String.valueOf(quantidadeDesinfetante));
        lblValorTotal10.setText(String.valueOf(quantidadeDesinfetante * precoDesinfetante));

    }//GEN-LAST:event_btnRemoverDesinfetanteActionPerformed

    private void btnAdicionarDesinfetanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDesinfetanteActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeDesinfetante = minhasCompras.adicionarUmDesinfetante();

        // Atualiza o preço do morango a cada clique
        double precoDesinfetante = 15.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeDesinfetante.setText(String.valueOf(quantidadeDesinfetante));
        lblValorTotal10.setText(String.valueOf(quantidadeDesinfetante * precoDesinfetante));

    }//GEN-LAST:event_btnAdicionarDesinfetanteActionPerformed

    private void btnRemoverFiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFiniActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeFini = minhasCompras.removerUmFini();

        // Atualiza o preço do morango a cada clique
        double precoFini = 5.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeFini.setText(String.valueOf(quantidadeFini));
        lblValorTotal9.setText(String.valueOf(quantidadeFini * precoFini));

    }//GEN-LAST:event_btnRemoverFiniActionPerformed

    private void btnRemover7beloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover7beloActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade7belo = minhasCompras.removerUm7belo();

        // Atualiza o preço do morango a cada clique
        double preco7belo = 5.0;

        lblQuantidade7belo.setText(String.valueOf(quantidade7belo));
        lblValorTotal8.setText(String.valueOf(quantidade7belo * preco7belo));

    }//GEN-LAST:event_btnRemover7beloActionPerformed

    private void btnAdicionar7beloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar7beloActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidade7belo = minhasCompras.adicionarUm7belo();

        // Atualiza o preço do morango a cada clique
        double preco7belo = 5.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidade7belo.setText(String.valueOf(quantidade7belo));
        lblValorTotal8.setText(String.valueOf(quantidade7belo * preco7belo));

    }//GEN-LAST:event_btnAdicionar7beloActionPerformed

    private void btnAdicionarCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCarneActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeCarne = minhasCompras.adicionarUmCarne();

        // Atualiza o preço do morango a cada clique
        double precoCarne = 25.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeCarne.setText(String.valueOf(quantidadeCarne));
        lblValorTotal2.setText(String.valueOf(quantidadeCarne * precoCarne));

    }//GEN-LAST:event_btnAdicionarCarneActionPerformed

    private void btnRemoverCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCarneActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeCarne = minhasCompras.removerUmCarne();

        // Atualiza o preço do morango a cada clique
        double precoCarne = 25.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeCarne.setText(String.valueOf(quantidadeCarne));
        lblValorTotal2.setText(String.valueOf(quantidadeCarne * precoCarne));

    }//GEN-LAST:event_btnRemoverCarneActionPerformed

    private void btnRemoverFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFrangoActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeFrango = minhasCompras.removerUmFrango();

        // Atualiza o preço do morango a cada clique
        double precoFrango = 17.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeFrango.setText(String.valueOf(quantidadeFrango));
        lblValorTotal3.setText(String.valueOf(quantidadeFrango * precoFrango));

    }//GEN-LAST:event_btnRemoverFrangoActionPerformed

    private void btnAdicionarFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFrangoActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeFrango = minhasCompras.adicionarUmFrango();

        // Atualiza o preço do morango a cada clique
        double precoFrango = 17.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeFrango.setText(String.valueOf(quantidadeFrango));
        lblValorTotal3.setText(String.valueOf(quantidadeFrango * precoFrango));

    }//GEN-LAST:event_btnAdicionarFrangoActionPerformed

    private void btnAdicionarPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPaoActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadePao = minhasCompras.adicionarUmPao();

        // Atualiza o preço do morango a cada clique
        double precoPao = 6.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadePao.setText(String.valueOf(quantidadePao));
        lblValorTotal6.setText(String.valueOf(quantidadePao * precoPao));

    }//GEN-LAST:event_btnAdicionarPaoActionPerformed

    private void btnRemoverBisnagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverBisnagaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeBisnaga = minhasCompras.removerUmBisnaga();

        // Atualiza o preço do morango a cada clique
        double precoBisnaga = 8.9;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeBisnaga.setText(String.valueOf(quantidadeBisnaga));
        lblValorTotal7.setText(String.valueOf(quantidadeBisnaga * precoBisnaga));

    }//GEN-LAST:event_btnRemoverBisnagaActionPerformed

    private void btnRemoverPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPaoActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadePao = minhasCompras.removerUmPao();

        // Atualiza o preço do morango a cada clique
        double precoPao = 6.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadePao.setText(String.valueOf(quantidadePao));
        lblValorTotal6.setText(String.valueOf(quantidadePao * precoPao));

    }//GEN-LAST:event_btnRemoverPaoActionPerformed

    private void btnAdicionarBisnagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarBisnagaActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeBisnaga = minhasCompras.adicionarUmBisnaga();

        // Atualiza o preço do morango a cada clique
        double precoBisnaga = 8.9;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeBisnaga.setText(String.valueOf(quantidadeBisnaga));
        lblValorTotal7.setText(String.valueOf(quantidadeBisnaga * precoBisnaga));

    }//GEN-LAST:event_btnAdicionarBisnagaActionPerformed

    private void btnAdicionarFiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFiniActionPerformed

        // Supondo que você tenha uma instância válida de Mercado
        int quantidadeFini = minhasCompras.adicionarUmFini();

        // Atualiza o preço do morango a cada clique
        double precoFini = 5.0;

        // Atualize a exibição da quantidade e do valor total
        lblQuantidadeFini.setText(String.valueOf(quantidadeFini));
        lblValorTotal9.setText(String.valueOf(quantidadeFini * precoFini));

    }//GEN-LAST:event_btnAdicionarFiniActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed

    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnVerificarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarCPFActionPerformed
        String cpfDigitado = txtCPF.getText();

        if (verificarCpfNoBancoDeDados(cpfDigitado)) {
            JOptionPane.showMessageDialog(null, "CPF válido. Pode fazer suas compras!");
            minhasCompras.setCpfCliente(cpfDigitado);
        } else {
            JOptionPane.showMessageDialog(null, "CPF não cadastrado. Faça o cadastro antes de continuar.");
        }
    }//GEN-LAST:event_btnVerificarCPFActionPerformed

    private void btnSalvarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarComprasActionPerformed
        double precoMorango = 10.0;
        double precoAmeixa = 8.0;
        double precoCoca = 10.0;
        double preco7belo = 10.0;
        double precoBisnaga = 8.9;
        double precoCarne = 25.0;
        double precoDesinfetante = 15.0;
        double precoDetergente = 6.0;
        double precoFini = 5.0;
        double precoFrango = 17.0;
        double precoGuarana = 10.0;
        double precoPao = 6.0;

        int quantidadeMorango = minhasCompras.adicionarUmMorango();
        int quantidadeAmeixa = minhasCompras.adicionarUmAmeixa();
        int quantidadeCoca = minhasCompras.adicionarUmCoca();
        int quantidade7belo = minhasCompras.adicionarUm7belo();
        int quantidadeBisnaga = minhasCompras.adicionarUmBisnaga();
        int quantidadeCarne = minhasCompras.adicionarUmCarne();
        int quantidadeDesinfetante = minhasCompras.adicionarUmDesinfetante();
        int quantidadeDetergente = minhasCompras.adicionarUmDetergente();
        int quantidadeFini = minhasCompras.adicionarUmFini();
        int quantidadeFrango = minhasCompras.adicionarUmFrango();
        int quantidadeGuarana = minhasCompras.adicionarUmGuarana();
        int quantidadePao = minhasCompras.adicionarUmPao();
// Solicitar que o cliente insira o CPF
        String cpfCliente = JOptionPane.showInputDialog("Digite o CPF:");

        // Verificar se o CPF é válido (você pode adicionar validações adicionais conforme necessário)
        if (cpfCliente != null && !cpfCliente.isEmpty()) {
            // Adicionar os produtos ao carrinho
            adicionarProdutoAoCarrinho(cpfCliente, "Morango", quantidadeMorango, precoMorango);
            adicionarProdutoAoCarrinho(cpfCliente, "Ameixa", quantidadeAmeixa, precoAmeixa);
            adicionarProdutoAoCarrinho(cpfCliente, "Coca", quantidadeCoca, precoCoca);
            adicionarProdutoAoCarrinho(cpfCliente, "7belo", quantidade7belo, preco7belo);
            adicionarProdutoAoCarrinho(cpfCliente, "Bisnaga", quantidadeBisnaga, precoBisnaga);
            adicionarProdutoAoCarrinho(cpfCliente, "Carne", quantidadeCarne, precoCarne);
            adicionarProdutoAoCarrinho(cpfCliente, "Desinfetante", quantidadeDesinfetante, precoDesinfetante);
            adicionarProdutoAoCarrinho(cpfCliente, "Detergente", quantidadeDetergente, precoDetergente);
            adicionarProdutoAoCarrinho(cpfCliente, "Fini", quantidadeFini, precoFini);
            adicionarProdutoAoCarrinho(cpfCliente, "Frango", quantidadeFrango, precoFrango);
            adicionarProdutoAoCarrinho(cpfCliente, "Guarana", quantidadeGuarana, precoGuarana);
            adicionarProdutoAoCarrinho(cpfCliente, "Pao", quantidadePao, precoPao);

            // Valor total da compra
            double valorTotal = calcularValorTotal();
            lblValorTotal.setText(String.valueOf(valorTotal));

            // Atualizar o texto do JLabel com o valor total
            lblValorTotal.setText(String.valueOf(valorTotal));

        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido. A compra não será registrada.");

            // Limpa as quantidades após salvar
            lblQuantidade.setText("0");
            lblQuantidadeAmeixa.setText("0");
            lblQuantidadeCoca.setText("0");
            lblQuantidadeDetergente.setText("0");
            lblQuantidadeGuarana.setText("0");
            lblQuantidadeDesinfetante.setText("0");
            lblQuantidadeFini.setText("0");
            lblQuantidade7belo.setText("0");
            lblQuantidadeCarne.setText("0");
            lblQuantidadeFrango.setText("0");
            lblQuantidadePao.setText("0");
            lblQuantidadeBisnaga.setText("0");

            if (carrinhoFrame != null) {
                carrinhoFrame.atualizarTabela(produtosSalvos);
            }

            // Carregar produtos do banco antes de atualizar o carrinho
            produtosSalvos = obterProdutosDoBanco(cpfCliente);

            // Atualizar a lista de produtos no carrinho
            atualizarCarrinho(carrinhoFrame.getTableCarrinho());
        }
    }//GEN-LAST:event_btnSalvarComprasActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        
        Pagamento novaTela = new Pagamento();
        novaTela.setVisible(true);
        
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaDoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaDoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaDoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaDoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaDoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAdicionar7belo;
    private javax.swing.JButton btnAdicionarAmeixa;
    private javax.swing.JButton btnAdicionarBisnaga;
    private javax.swing.JButton btnAdicionarCarne;
    private javax.swing.JButton btnAdicionarCoca;
    private javax.swing.JButton btnAdicionarDesinfetante;
    private javax.swing.JButton btnAdicionarDetergente;
    private javax.swing.JButton btnAdicionarFini;
    private javax.swing.JButton btnAdicionarFrango;
    private javax.swing.JButton btnAdicionarGuarana;
    private javax.swing.JButton btnAdicionarPao;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRemover7belo;
    private javax.swing.JButton btnRemoverAmeixa;
    private javax.swing.JButton btnRemoverBisnaga;
    private javax.swing.JButton btnRemoverCarne;
    private javax.swing.JButton btnRemoverCoca;
    private javax.swing.JButton btnRemoverDesinfetante;
    private javax.swing.JButton btnRemoverDetergente;
    private javax.swing.JButton btnRemoverFini;
    private javax.swing.JButton btnRemoverFrango;
    private javax.swing.JButton btnRemoverGuarana;
    private javax.swing.JButton btnRemoverPao;
    private javax.swing.JButton btnSalvarCompras;
    private javax.swing.JButton btnVerificarCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidade7belo;
    private javax.swing.JLabel lblQuantidadeAmeixa;
    private javax.swing.JLabel lblQuantidadeBisnaga;
    private javax.swing.JLabel lblQuantidadeCarne;
    private javax.swing.JLabel lblQuantidadeCoca;
    private javax.swing.JLabel lblQuantidadeDesinfetante;
    private javax.swing.JLabel lblQuantidadeDetergente;
    private javax.swing.JLabel lblQuantidadeFini;
    private javax.swing.JLabel lblQuantidadeFrango;
    private javax.swing.JLabel lblQuantidadeGuarana;
    private javax.swing.JLabel lblQuantidadePao;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotal1;
    private javax.swing.JLabel lblValorTotal10;
    private javax.swing.JLabel lblValorTotal11;
    private javax.swing.JLabel lblValorTotal2;
    private javax.swing.JLabel lblValorTotal3;
    private javax.swing.JLabel lblValorTotal4;
    private javax.swing.JLabel lblValorTotal5;
    private javax.swing.JLabel lblValorTotal6;
    private javax.swing.JLabel lblValorTotal7;
    private javax.swing.JLabel lblValorTotal8;
    private javax.swing.JLabel lblValorTotal9;
    private javax.swing.JLabel lblValorTotalMorango;
    private javax.swing.JFormattedTextField txtCPF;
    // End of variables declaration//GEN-END:variables

    private boolean verificarCpfNoBancoDeDados(String cpfDigitado) {

        ConexaoDAO clienteDAO = new ConexaoDAO(); // Substitua pelo nome da sua classe DAO
        try {
            return clienteDAO.verificarExistenciaCPF(cpfDigitado);
        } catch (SQLException e) {
            e.printStackTrace();
            return false; // Tratar a exceção conforme necessário
        }

    }

    private void atualizarCarrinho(JTable tableCarrinho) {
        // Certifique-se de que carrinhoFrame está inicializado
        if (carrinhoFrame == null) {
            carrinhoFrame = new CarrinhoDeCompras();
        }

        // Exibir os produtos salvos na tela do carrinho
        carrinhoFrame.atualizarTabela(produtosSalvos);
        carrinhoFrame.setVisible(true);

    }

    private void adicionarProdutoAoCarrinho(String cpfCliente, String nomeProduto, int quantidade, double precoProduto) {
        if (quantidade > 0) {
            // Adicionar o produto ao carrinho associado ao CPF do cliente
            produtosSalvos.add(new ProdutoCarrinho(cpfCliente, nomeProduto, quantidade, precoProduto));
            // Atualizar a tabela no carrinho
            if (carrinhoFrame != null) {
                carrinhoFrame.atualizarTabela(produtosSalvos);
            }
            // Salvar o produto no banco de dados
            salvarProdutoCarrinho(cpfCliente, nomeProduto, quantidade, precoProduto);
        }
    }

    private void salvarProdutoCarrinho(String cpfCliente, String nomeProduto, int quantidade, double precoProduto) {
        try (Connection conexao = obterConexao()) {
            String sql = "INSERT INTO carrinhocompras (cpf_cliente, produto, quantidade, valor_gasto) VALUES (?, ?, ?, ?)";

            try (PreparedStatement stmt = conexao.prepareStatement(sql)) {
                stmt.setString(1, cpfCliente);
                stmt.setString(2, nomeProduto);
                stmt.setInt(3, quantidade);
                stmt.setDouble(4, precoProduto);
                stmt.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Lide com o erro conforme necessário.
        }
    }

// Método para ler produtos do banco de dados
    private List<ProdutoCarrinho> obterProdutosDoBanco(String cpfCliente) {
        List<ProdutoCarrinho> produtos = new ArrayList<>();

        try (Connection conexao = obterConexao()) {
            String sql = "SELECT * FROM carrinhocompras WHERE cpf_cliente = ?";

            try (PreparedStatement stmt = conexao.prepareStatement(sql)) {
                stmt.setString(1, cpfCliente);

                try (ResultSet resultado = stmt.executeQuery()) {
                    while (resultado.next()) {
                        String nome = resultado.getString("produto");
                        int quantidade = resultado.getInt("quantidade");
                        double valor = resultado.getDouble("valor_gasto");

                        produtos.add(new ProdutoCarrinho(cpfCliente, nome, quantidade, valor));
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return produtos;
    }

    private Connection obterConexao() {
        Connection conexao = null;

        try {
            // Carregue o driver JDBC.
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Configurações para a conexão com o banco de dados.
            String url = "jdbc:mysql://localhost:3306/mercado";
            String usuario = "pedroo";
            String senha = "123";

            // Estabeleça a conexão
            conexao = DriverManager.getConnection(url, usuario, senha);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }

        return conexao;
    }

    private double calcularValorTotal() {
        double valorTotal = 0.0;

        // Calcular o valor total somando os valores de cada produto no carrinho
        for (ProdutoCarrinho produto : produtosSalvos) {
            valorTotal += produto.getValor() * produto.getQuantidade();
        }

        return valorTotal;
    }

}
